"""Combine every project document into one file: HANDBOOK.md.

HANDBOOK.md has two parts:

* Part I, "Understand it", is written by hand at the top of the file. It is
  the integrated explanation of the whole project, and this script never
  touches it.
* Part II, "Every document, verbatim", is everything after the marker line.
  This script regenerates it from the files in DOCS, in reading order.

Run it whenever a document changes:

    python scripts/build_handbook.py

Each document keeps its own words. Three mechanical changes make them read as
one file:

1. Headings move down two levels, so every document sits under its own
   Part II heading and the outline stays readable. Lines inside code fences
   are left alone.
2. Relative links and images are re-pointed so they still resolve from the
   repository root, where HANDBOOK.md lives.
3. A YAML front-matter block (DESIGN.md has one) becomes a fenced yaml block
   instead of rendering as a stray table.
"""
from __future__ import annotations

import posixpath
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "HANDBOOK.md"
MARKER = "<!-- PART II: generated by scripts/build_handbook.py; edit the source documents, not below this line -->"

#: (section, path, what it is). Reading order: orientation, science, evidence,
#: frontend, roadmap, operations, learning, then the design specs by date.
DOCS = [
    ("A. Orientation", "README.md", "the public front page of the repository"),
    ("A. Orientation", "PRODUCT.md", "who the product is for and what it must never do"),
    ("A. Orientation", "docs/PROJECT_GUIDE.md", "the system map: architecture, science and extension recipes"),
    ("B. The science", "LOGIC.md", "the original specification: problem, definitions, method"),
    ("B. The science", "DATA.md", "data sources, licences, and what is or is not in git"),
    ("B. The science", "TECHNICAL_STUDY_GUIDE.md", "the long-form study guide with self-checks"),
    ("B. The science", "PROJECT_BLUEPRINT.md", "the original build blueprint"),
    ("C. Decisions and evidence", "DECISIONS.md", "every decision D-001 to D-031, with its evidence"),
    ("C. Decisions and evidence", "docs/FIGURES.md", "what each published figure shows"),
    ("C. Decisions and evidence", "docs/PREREGISTRATION_S1.md", "S1 registration: the model vs real ENS spread, 2022"),
    ("C. Decisions and evidence", "docs/PREREGISTRATION_S1B.md", "S1b registration: the rolling-origin backtest, 2019-2021"),
    ("C. Decisions and evidence", "docs/PREREGISTRATION_S1C.md", "S1c registration: model + ENS vs ENS alone"),
    ("C. Decisions and evidence", "docs/PREREGISTRATION_S3.md", "S3 registration: the three-candidate slate and its promotion rule"),
    ("C. Decisions and evidence", "docs/PREREGISTRATION_S3A_CONFIRM.md", "S3a-C registration: the untouched-2018 confirmation"),
    ("C. Decisions and evidence", "docs/PREREGISTRATION_S3B.md", "S3b registration: the temporal (GRU) candidate"),
    ("C. Decisions and evidence", "docs/PREREGISTRATION_S3C.md", "S3c registration: the spatial (CNN) candidate"),
    ("C. Decisions and evidence", "docs/PREREGISTRATION_B2.md", "B2 registration: the operational state, non-inferiority"),
    ("C. Decisions and evidence", "docs/PREREGISTRATION_B5.md", "B5 registration: spatial + ENS against the served combination"),
    ("C. Decisions and evidence", "docs/PREREGISTRATION_B3.md", "B3 registration: beta-family tail calibration"),
    ("C. Decisions and evidence", "docs/PREREGISTRATION_B4.md", "B4 registration: a Day 1-2 combiner"),
    ("C. Decisions and evidence", "docs/PREREGISTRATION_V3.md", "V3 registration: B3 and B4 on the spatial base"),
    ("D. Frontend", "FRONTEND_LOGIC.md", "the law for every page: claims, honesty, states"),
    ("D. Frontend", "docs/FRONTEND_BUILT.md", "what was built before the redesign"),
    ("D. Frontend", "FRONTEND_HANDOFF.md", "the earlier frontend handoff"),
    ("D. Frontend", "HANDOFF_VOLUME.md", "the volume view handoff"),
    ("D. Frontend", "docs/FRONTEND_AUDIT.md", "the baseline audit, findings F1 to F16"),
    ("D. Frontend", "DESIGN.md", "the design system as built"),
    ("D. Frontend", "docs/DESIGN_DECISIONS.md", "why it looks this way, and which rule won each conflict"),
    ("D. Frontend", "docs/FRONTEND_IMPLEMENTATION_REPORT.md", "what the redesign fixed, with evidence"),
    ("E. Roadmap", "docs/POST_FRONTEND_TECHNICAL_AUDIT.md", "the ML and data audit, fourteen questions"),
    ("E. Roadmap", "docs/FEATURE_AVAILABILITY_MATRIX.md", "every input: when it exists, and whether it is legal live"),
    ("E. Roadmap", "docs/REALTIME_SOURCE_MATRIX.md", "candidate live sources, checked against official pages"),
    ("E. Roadmap", "docs/ML_RESEARCH_BACKLOG.md", "what to study next, B1 to B8"),
    ("F. Operations", "docs/DEPLOY.md", "how to deploy the read-only image"),
    ("F. Operations", "docs/CLOUD_AND_CICD_PLAN.md", "what CI proves, and gaps C1 to C9"),
    ("G. Learning and handoff", "docs/LEARNING_PATH.md", "modules tied to real files and commands"),
    ("G. Learning and handoff", "HANDOFF.md", "the earlier project handoff"),
    ("G. Learning and handoff", "docs/SESSION_HANDOFF.md", "the latest session handoff"),
    ("H. Design specs", "docs/superpowers/specs/2026-09-20-volumetric-risk-field-design.md", "the volume view"),
    ("H. Design specs", "docs/superpowers/specs/2026-09-23-volume-geography-flythrough-design.md", "volume geography and fly-through"),
    ("H. Design specs", "docs/superpowers/specs/2026-09-23-s1-settle-ens-design.md", "S1"),
    ("H. Design specs", "docs/superpowers/specs/2026-09-25-s1b-rolling-origin-backtest-design.md", "S1b"),
    ("H. Design specs", "docs/superpowers/specs/2026-09-25-serve-combination-design.md", "serving the combination (D-030)"),
    ("H. Design specs", "docs/superpowers/specs/2026-09-25-s3a-candidate-harness-mlp-design.md", "S3a, the MLP"),
    ("H. Design specs", "docs/superpowers/specs/2026-09-27-s3b-temporal-candidate-design.md", "S3b, the GRU"),
    ("H. Design specs", "docs/superpowers/specs/2026-09-28-s3c-spatial-candidate-design.md", "S3c, the spatial CNNs (scored: D-032)"),
    ("H. Design specs", "docs/superpowers/specs/2026-10-06-b2-operational-analysis-design.md", "B2, the operational state with derived TCWV"),
    ("H. Design specs", "docs/superpowers/specs/2026-10-06-b5-serving-decision-design.md", "B5, the serving decision"),
    ("H. Design specs", "docs/superpowers/specs/2026-10-06-b3-b4-combiner-refinements-design.md", "B3 and B4, combiner refinements"),
    ("H. Design specs", "docs/superpowers/specs/2026-10-06-v030-serve-spatial-design.md", "store v0.3.0, serving the spatial model"),
]

#: Not combined: the step-by-step build plans. They are long task scripts
#: with full code, and the code they produced is the real source now.
PLANS_DIR = "docs/superpowers/plans"

FENCE = re.compile(r"^(\s*)(`{3,}|~{3,})")
HEADING = re.compile(r"^(#{1,6})(\s+.*)$")
LINK = re.compile(r"(!?\[[^\]]*\]\()([^)\s]+)((?:\s+\"[^\"]*\")?\))")


def slug(text: str) -> str:
    """GitHub's heading anchor: lowercase, drop punctuation, spaces to hyphens."""
    s = text.strip().lower()
    s = re.sub(r"[^\w\- ]", "", s)
    return s.replace(" ", "-")


def frontmatter_to_yaml(text: str) -> str:
    if not text.startswith("---\n"):
        return text
    end = text.find("\n---\n", 4)
    if end < 0:
        return text
    return "```yaml\n" + text[4:end] + "\n```\n" + text[end + 5:]


def relink(target: str, src_dir: str) -> str:
    if re.match(r"^([a-z][a-z0-9+.-]*:|#|/)", target, re.I):
        return target
    path, _, frag = target.partition("#")
    if not path:
        return target
    fixed = posixpath.normpath(posixpath.join(src_dir, path)) if src_dir else path
    return fixed + ("#" + frag if frag else "")


def opens_fence(line: str):
    """The fence a line opens, or None. CommonMark: a backtick fence's info
    string may not contain a backtick, so ````registration```` at the start of
    a line is inline code, not a fence."""
    m = FENCE.match(line)
    if not m:
        return None
    marks = m.group(2)
    if marks[0] == "`" and "`" in line[m.end():]:
        return None
    return marks


def closes_fence(line: str, fence: str) -> bool:
    """A closing fence is the same character, at least as long, and nothing else."""
    s = line.strip()
    return len(s) >= len(fence) and set(s) == {fence[0]}


def transform(text: str, src: str) -> str:
    src_dir = posixpath.dirname(src)
    out, fence = [], None
    for line in frontmatter_to_yaml(text).splitlines():
        if fence:
            if closes_fence(line, fence):
                fence = None
            out.append(line)
            continue
        opened = opens_fence(line)
        if opened:
            fence = opened
            out.append(line)
            continue
        h = HEADING.match(line)
        if h:
            line = "#" * min(6, len(h.group(1)) + 2) + h.group(2)
        line = LINK.sub(lambda mm: mm.group(1) + relink(mm.group(2), src_dir) + mm.group(3), line)
        out.append(line)
    if fence:
        # A source that ends inside a code block would swallow every document
        # after it once combined; close it here.
        out.append(fence)
    return "\n".join(out).rstrip() + "\n"


def part_two() -> str:
    parts = ["# Part II. Every document, verbatim", ""]
    parts.append("Every project document follows, in reading order. Each keeps its own "
                 "words; only heading levels and relative links were adjusted so they "
                 "read as one file. Part I above is the explanation; this part is the "
                 "evidence and the detail. When two documents disagree, the newer "
                 "decision record (the highest D-number in DECISIONS.md) wins.")
    parts.append("")
    parts.append("Contents of Part II:")
    parts.append("")
    section = None
    for i, (sec, path, what) in enumerate(DOCS, 1):
        if sec != section:
            section = sec
            parts.append(f"- **{sec}**")
        title = f"II.{i} {path}"
        parts.append(f"  - [{title}](#{slug(title)}): {what}")
    plans = sorted((ROOT / PLANS_DIR).glob("*.md"))
    parts.append("")
    parts.append(f"Not combined: the {len(plans)} step-by-step build plans in `{PLANS_DIR}/`. "
                 "They are task scripts with full code; the code they produced is the source of truth now.")
    parts.append("")
    for i, (sec, path, what) in enumerate(DOCS, 1):
        text = (ROOT / path).read_text(encoding="utf-8")
        parts.append("---")
        parts.append("")
        parts.append(f"## II.{i} {path}")
        parts.append("")
        parts.append(f"*{what}.* Source: `{path}`.")
        parts.append("")
        parts.append(transform(text, path))
    return "\n".join(parts).rstrip() + "\n"


def main() -> None:
    missing = [p for _, p, _ in DOCS if not (ROOT / p).exists()]
    if missing:
        raise SystemExit(f"missing documents: {missing}")
    head = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
    if MARKER not in head:
        raise SystemExit(f"{OUT.name} has no Part II marker; write Part I first, ending with:\n{MARKER}")
    head = head.split(MARKER)[0].rstrip() + "\n\n" + MARKER + "\n\n"
    OUT.write_text(head + part_two(), encoding="utf-8", newline="\n")
    n = OUT.read_text(encoding="utf-8").count("\n")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(DOCS)} documents combined, {n:,} lines")


if __name__ == "__main__":
    main()
